#ifndef GLOBALDEFINES_H_INCLUDED
#define GLOBALDEFINES_H_INCLUDED

//precision
#define FINAL_PRECISION 15

//debug defines
#define DEBUG_TRANSFORMER_SHOWELEMENTS              true
#define DEBUG_TRANSFORMER_SETCALCULATIONELEMENTS    true
#define DEBUG_CALCULATOR_RECURSIVECHUNKYCALCULATION true
#define DEBUG_CALCULATOR_CALCULATEDAUGS             true
#define DEBUG_CALCULATOR_CALCULATESPECIALS          true
#define DEBUG_CALCULATOR_SKAICSPECIAL               true
#define DEBUG_TRANSFORMER_SHOWCALCELEMENTCONTENTS   true
#define DEBUG_CALCULATOR_IDENTIFYNEGATIVES          false


#endif // GLOBALDEFINES_H_INCLUDED
