#ifndef GLOBALDEFINES_H_INCLUDED
#define GLOBALDEFINES_H_INCLUDED

#include "tools/debug.h"

//VERSION
#define VERSION "v0.5.1 pre" //Cool!

//precision
#define FINAL_PRECISION 15

//debug defines
#define DEBUGGER_DEBUGMODE   DEBUG_TO_SCREEN

#define DEBUG_CALCULATOR_SENDSTRING                 false
#define DEBUG_CALCULATOR_RECURSIVECHUNKYCALCULATION true
#define DEBUG_CALCULATOR_CALCULATEDAUGS             false
#define DEBUG_CALCULATOR_CALCULATESPECIALS          false
#define DEBUG_CALCULATOR_SKAICSPECIAL               false
#define DEBUG_CALCULATOR_IDENTIFYNEGATIVES          true

#define DEBUG_TRANSFORMER_SHOWELEMENTS              true
#define DEBUG_TRANSFORMER_SETCALCULATIONELEMENTS    false
#define DEBUG_TRANSFORMER_SHOWCALCELEMENTCONTENTS   false
//debug define end

#endif // GLOBALDEFINES_H_INCLUDED
